[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "k_runner"
version = "1.0"
description = "This module is for smartly running system commands and processing their io streams."
license = {file = "LICENSE"}
dependencies = [
	"lxml",
	"paths @ git+https://github.com/TheHeadlessSourceMan/paths.git",
	"psutil",
	"pywin32; sys_platform == 'win32'",
]

[tool.hatch.build.targets.wheel.force-include]
"LICENSE" = "k_runner/LICENSE"
"__init__.py" = "k_runner/__init__.py"
"_kRunnerToolsLinux.py" = "k_runner/_kRunnerToolsLinux.py"
"_kRunnerToolsWindows.py" = "k_runner/_kRunnerToolsWindows.py"
"commandTag.py" = "k_runner/commandTag.py"
"dataRecievedCallbacks.py" = "k_runner/dataRecievedCallbacks.py"
"environmentVariables.py" = "k_runner/environmentVariables.py"
"exceptions.py" = "k_runner/exceptions.py"
"expect.py" = "k_runner/expect.py"
"filterRun.py" = "k_runner/filterRun.py"
"kRunnerTools.py" = "k_runner/kRunnerTools.py"
"multiExecute.py" = "k_runner/multiExecute.py"
"osrun.py" = "k_runner/osrun.py"
"osRunJob.py" = "k_runner/osRunJob.py"
"osRunResult.py" = "k_runner/osRunResult.py"
"processWatcher.py" = "k_runner/processWatcher.py"
"pyErrRun.py" = "k_runner/pyErrRun.py"
"runPythonFile.py" = "k_runner/runPythonFile.py"
"runSomething.py" = "k_runner/runSomething.py"
"settings.py" = "k_runner/settings.py"
"py.typed" = "k_runner/py.typed"
"cmdline/__init__.py" = "k_runner/cmdline/__init__.py"
"cmdline/asCommandLine.py" = "k_runner/cmdline/asCommandLine.py"
"cmdline/commandLine.py" = "k_runner/cmdline/commandLine.py"
"cmdline/commandLineStringHelpers.py" = "k_runner/cmdline/commandLineStringHelpers.py"
"cmdline/helpfiles.py" = "k_runner/cmdline/helpfiles.py"
"cmdline/helpstringParserExperimental.py" = "k_runner/cmdline/helpstringParserExperimental.py"
"processes/__init__.py" = "k_runner/processes/__init__.py"
"processes/asProcess.py" = "k_runner/processes/asProcess.py"
"processes/exceptions.py" = "k_runner/processes/exceptions.py"
"processes/find.py" = "k_runner/processes/find.py"
"processes/interpreterProcesses.py" = "k_runner/processes/interpreterProcesses.py"
"processes/possiblyRunningApplication.py" = "k_runner/processes/possiblyRunningApplication.py"
"processes/priority.py" = "k_runner/processes/priority.py"
"processes/priorityConstants.py" = "k_runner/processes/priorityConstants.py"
"processes/process.py" = "k_runner/processes/process.py"
"processes/processGroup.py" = "k_runner/processes/processGroup.py"
"processes/processStats.py" = "k_runner/processes/processStats.py"
"processes/windowsPriority.py" = "k_runner/processes/windowsPriority.py"
"ui/__init__.py" = "k_runner/ui/__init__.py"
"ui/asUiComponent.py" = "k_runner/ui/asUiComponent.py"
"ui/component.py" = "k_runner/ui/component.py"
"ui/componentGroup.py" = "k_runner/ui/componentGroup.py"
"ui/desktop.py" = "k_runner/ui/desktop.py"
"ui/find.py" = "k_runner/ui/find.py"
"ui/keyboardKeys.py" = "k_runner/ui/keyboardKeys.py"
"ui/window.py" = "k_runner/ui/window.py"
"ui/windowHandleType.py" = "k_runner/ui/windowHandleType.py"
"ui/windowScreenshot.py" = "k_runner/ui/windowScreenshot.py"