#!/usr/bin/python
"""
This is helper for creating function calls that run command line
programs
"""
from .helpfiles import HelpSystemEntry


class CmdLineWrapper(HelpSystemEntry):
    """
    A tool to create function calls from command line apps
    """
    def __init__(self,app=None):
        HelpSystemEntry.__init__(self,app)

    def createPythonWrapper(self,createMainFunction=False):
        """
        :createMainFunction: Generally, creating a command line
            app to call a command line app is
            rather pointless.  Still, can be handy for testing.
        """
        opts=self.getCommandLineOptions()
        if len(opts)<1:
            return ''
        code=[]
        code.append('#!/usr/bin/python')
        code.append('"""')
        code.append('This is wrapper for the \''+self.name+'\' command line program') # noqa: E501 # pylint: disable = line-too-long
        if self.description:
            code.append('')
            for line in self.getDescription(False,78).split('\n'):
                code.append(line)
        code.append('')
        code.append('Generated by: The cmdlinewrap.py utility')
        code.append('"""')
        code.append('\n')
        code.append('def '+self.name+'(*args,**kwargs):')
        code.append('\t"""')
        if self.description:
            code.append('\tDESCRIPTION:')
            for line in self.getDescription(False,70).split('\n'):
                code.append('\t\t'+line)
        code.append('\tPARAMETERS:')
        for o in opts:
            code.append('\t\t'+o.getHelp())
        code.append('\tRETURNS:')
        code.append('\t\tout,err')
        code.append('\t"""')
        code.append('\toptions={')
        for o in opts:
            opt=o.options[0].replace('[','').replace(']','')
            code.append('\t\t\''+o.name+'\':[\''+opt+'\'],')
        code.append('\t}')
        # TODO: May want to check if the app exists first??
        code.append('\tcmd=\''+self.app+'\'')
        code.append('\tfor k,v in kwargs.items():')
        code.append('\t\tif options.has_key(k):')
        code.append('\t\t\to=options[k][0].split(\'=\',1)')
        code.append('\t\t\tcmd=cmd+\' \'+o[0]')
        code.append('\t\t\tif len(o)>1:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\'="\'+(\' \'.join(v))+\'"\'')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+\'=\'+str(v)')
        code.append('\t\t\telse:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\' \'+(\' \'.join(v))')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+str(v)')
        code.append('\t\telse:')
        code.append('\t\t\tprint \'WARN: Unregistered arg: \'+k')
        code.append('\tif len(args)>0:')
        code.append('\t\tcmd=cmd+\' \'+(\' \'.join(args))')
        # TODO: Add any option parameters here
        code.append('\tprint \'Calling: \\n   \'+cmd # Uncomment for debugging purposes') # noqa: E501 # pylint: disable = line-too-long
        code.append('\timport subprocess')
        code.append('\tout,err=subprocess.Popen(cmd,stderr=subprocess.PIPE,stdout=subprocess.PIPE,shell=True).communicate()') # noqa: E501 # pylint: disable = line-too-long
        code.append('\treturn out,err')
        if createMainFunction:
            code.append('\n')
            code.append('if __name__ == \'__main__\':')
            code.append('\timport sys')
            code.append('\titems=[]')
            code.append('\toptions={}')
            code.append('\ttry: # in newer python, we can preserve argument ordering!') # noqa: E501 # pylint: disable = line-too-long
            code.append('\t\tfrom collections import OrderedDict')
            code.append('\t\toptions=OrderedDict()')
            code.append('\texcept:')
            code.append('\t\tpass')
            code.append('\tdef AddOption(opt):')
            code.append('\t\topt=opt.split(\'=\',1)')
            code.append('\t\tif len(opt)>1:')
            code.append('\t\t\toptions[opt[0]]=opt[1]')
            code.append('\t\telse:')
            code.append('\t\t\toptions[opt[0]]=None')
            code.append('\tfor arg in sys.argv[1:]:')
            code.append('\t\tif arg[0]==\'-\':')
            code.append('\t\t\tif arg[1]==\'-\':')
            code.append('\t\t\t\tAddOption(arg[2:])')
            code.append('\t\t\telse:')
            code.append('\t\t\t\tfor a in arg[1:]:')
            code.append('\t\t\t\t\tAddOption(a)')
            code.append('\t\telse:')
            code.append('\t\t\titems.append(arg)')
            code.append('\tout,err='+self.name+'(*items,**options)')
            code.append('\terr=err.strip()')
            code.append('\tif err!=\'\':')
            code.append('\t\tprint err')
            code.append('\telse:')
            code.append('\t\tprint out')
        return '\n'.join(code)

    def savePythonWrapper(self,filename,createMainFunction=False):
        """
        Create a python wrapper for the command line application
        and save it to file
        """
        data=self.createPythonWrapper(createMainFunction=createMainFunction)
        if data:
            try:
                f=open(filename,'w')
                f.write(data)
                f.close()
                return True
            except Exception:
                print('ERR: Unable to open \"'+filename+'\" for writing.')
                return False
        print('ERR: No data found.  File not saved.')
        return False


if __name__ == '__main__':
    """
    This generates a command line wrapper... from the command line.
    """
    import sys
    # Use the Psyco python accelerator if available
    # See:
    #     http://psyco.sourceforge.net
    try:
        import psyco
        psyco.full() # accelerate this program
    except ImportError:
        pass
    printhelp=False
    cmd=None
    infoFrom=[]
    out=[]
    for arg in sys.argv[1:]:
        if cmd is None:
            if arg[0]=='-':
                if arg[1]=='-':
                    arg=arg.split('=',1)
                    if arg[0]=='--out':
                        out.append(arg[-1])
                    else:
                        print('Unrecognized parameter: '+arg[0])
                        printhelp=True
                else:
                    print('Unrecognized parameter: '+arg)
                    printhelp=True
            else:
                cmd=arg
        else:
            infoFrom.append(arg)
    if cmd is None:
        print('ERR: no cmd specified.')
        printhelp=True
    if len(out)<1:
        print('ERR: no outputs specified.')
        printhelp=True
    if printhelp:
        print('USAGE:')
        print('\tcmdlinewrapper.py --out=filename [--out=filename ...] cmd [get_info_from]') # noqa: E501 # pylint: disable = line-too-long
        print('PARAMS:')
        print('\t--out=<filename> ..... output to save.  If filename is just an extension, save to stdout.') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcurrently supports: only ".py"')
        print('EXAMPLES:')
        print('\tAutomatically generate python wrapper for "ls" to the file "ls.py":') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcmdlinewrapper.py --out=ls.py ls')
        print('\tAutomatically generate python wrapper for "ls" to stdout:')
        print('\t\tcmdlinewrapper.py --out=.py ls')
        print('\tGenerate the wrapper by calling the command with --help:')
        print('\t\tcmdlinewrapper.py --out=.py ls ls --help')
        print('\t... or just let cmdlinewrapper make the assumption:')
        print('\t\tcmdlinewrapper.py --out=.py ls --help')
        print('\tGenerate the wrapper from the command\'s manpage:')
        print('\t\tcmdlinewrapper.py --out=.py ls man')
        print('\tGenerate the wrapper from a webpage:')
        print('\t\tcmdlinewrapper.py --out=.py ls http://www.foo.com/ls.html')
        print('\t... or a local file:')
        print('\t\tcmdlinewrapper.py --out=.py ls ls.html')
        print('\t... same goes for text files:')
        print('\t\tcmdlinewrapper.py --out=.py ls README.txt')
    else:
        wrapper=CmdLineWrapper(cmd)
        wrapper.getCommandLineOptions(' '.join(infoFrom))
        for o in out:
            extn=o.rsplit('.',1)
            if extn[-1]=='py':
                if len(extn)<2 or extn[0]=='' or extn[0]=='-':
                    print(wrapper.createPythonWrapper(createMainFunction=True))
                else:
                    wrapper.savePythonWrapper(o,createMainFunction=True)
