#!/usr/bin/python
"""
This is helper for creating function calls that run command line
programs
"""
import typing
from paths import asUrl,UrlCompatible
from .helpfiles import HelpSystemEntry
from .asCommandLine import CommandLineCompatible


def argvToString(argv:typing.Iterable[str])->str:
    """
    convert a list of arguments into a string
    does helpful things like adding quotes
    """
    ret=[]
    for arg in argv:
        if arg.find(' ')>=0 or arg.find('"')>=1:
            arg=arg.replace('\\','\\\\').replace('"','\\"')
            arg=f'"{arg}"'
        ret.append(arg)
    return ' '.join(ret)


class CommandLineWrapper(HelpSystemEntry):
    """
    A tool to create function calls from command line apps
    """
    def __init__(self,app:typing.Optional[CommandLineCompatible]=None):
        HelpSystemEntry.__init__(self,app)

    def createPythonWrapperCode(self,createMainFunction:bool=False)->str:
        """
        Create python code (in a string) that wraps the command line call

        :createMainFunction: Generally, creating a command line
            app to call a command line app is
            rather pointless.  Still, can be handy for testing.
        """
        opts=tuple(self.getCommandLineOptions())
        if len(opts)<1:
            return ''
        code=[]
        code.append('#!/usr/bin/python')
        code.append('"""')
        code.append(f'This is wrapper for the \'{self.name}\' command line program') # noqa: E501 # pylint: disable = line-too-long
        if self.description:
            code.append('')
            for line in self.getDescription(False,lineWrap=78).split('\n'):
                code.append(line)
        code.append('')
        code.append('Generated by: The cmdlinewrap.py utility')
        code.append('"""')
        code.append('\n')
        code.append(f'def {self.name}(*args,**kwargs):')
        code.append('\t"""')
        if self.description:
            code.append('\tDESCRIPTION:')
            for line in self.getDescription(False,lineWrap=70).split('\n'):
                code.append('\t\t'+line)
        code.append('\tPARAMETERS:')
        for o in opts:
            code.append('\t\t'+o.getHelp())
        code.append('\tRETURNS:')
        code.append('\t\tout,err')
        code.append('\t"""')
        code.append('\toptions={')
        for o in opts:
            opt=''
            for opt in o.options:
                break
            opt=opt.replace('[','').replace(']','')
            code.append('\t\t\''+o.name+'\':[\''+opt+'\'],')
        code.append('\t}')
        # TODO: May want to check if the app exists first??
        code.append(f'\tcmd=\'{self.app}\'')
        code.append('\tfor k,v in kwargs.items():')
        code.append('\t\tif options.has_key(k):')
        code.append('\t\t\to=options[k][0].split(\'=\',1)')
        code.append('\t\t\tcmd=cmd+\' \'+o[0]')
        code.append('\t\t\tif len(o)>1:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\'="\'+(\' \'.join(v))+\'"\'')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+\'=\'+str(v)')
        code.append('\t\t\telse:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\' \'+(\' \'.join(v))')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+str(v)')
        code.append('\t\telse:')
        code.append('\t\t\tprint \'WARN: Unregistered arg: \'+k')
        code.append('\tif len(args)>0:')
        code.append('\t\tcmd=cmd+\' \'+(\' \'.join(args))')
        # TODO: Add any option parameters here
        code.append('\tprint \'Calling: \\n   \'+cmd # Uncomment for debugging purposes') # noqa: E501 # pylint: disable = line-too-long
        code.append('\timport subprocess')
        code.append('\tout,err=subprocess.Popen(cmd,stderr=subprocess.PIPE,stdout=subprocess.PIPE,shell=True).communicate()') # noqa: E501 # pylint: disable = line-too-long
        code.append('\treturn out,err')
        if createMainFunction:
            code.append('\n')
            code.append('if __name__ == \'__main__\':')
            code.append('\timport sys')
            code.append('\titems=[]')
            code.append('\toptions={}')
            code.append('\ttry: # in newer python, we can preserve argument ordering!') # noqa: E501 # pylint: disable = line-too-long
            code.append('\t\tfrom collections import OrderedDict')
            code.append('\t\toptions=OrderedDict()')
            code.append('\texcept:')
            code.append('\t\tpass')
            code.append('\tdef AddOption(opt):')
            code.append('\t\topt=opt.split(\'=\',1)')
            code.append('\t\tif len(opt)>1:')
            code.append('\t\t\toptions[opt[0]]=opt[1]')
            code.append('\t\telse:')
            code.append('\t\t\toptions[opt[0]]=None')
            code.append('\tfor arg in sys.argv[1:]:')
            code.append('\t\tif arg[0]==\'-\':')
            code.append('\t\t\tif arg[1]==\'-\':')
            code.append('\t\t\t\tAddOption(arg[2:])')
            code.append('\t\t\telse:')
            code.append('\t\t\t\tfor a in arg[1:]:')
            code.append('\t\t\t\t\tAddOption(a)')
            code.append('\t\telse:')
            code.append('\t\t\titems.append(arg)')
            code.append(f'\tout,err={self.name}(*items,**options)')
            code.append('\terr=err.strip()')
            code.append('\tif err!=\'\':')
            code.append('\t\tprint err')
            code.append('\telse:')
            code.append('\t\tprint out')
        return '\n'.join(code)
    createPythonWrapper=createPythonWrapperCode

    def savePythonWrapper(self,
        filename:UrlCompatible,
        createMainFunction:bool=False
        )->bool:
        """
        Create a python wrapper for the command line application
        and save it to file
        """
        filename=asUrl(filename)
        data=self.createPythonWrapper(createMainFunction=createMainFunction)
        if data:
            filename.write(data)
            return True
        print('ERR: No data found.  File not saved.')
        return False
CommandLine=CommandLineWrapper
CmdLine=CommandLineWrapper
CmdLineWrapper=CommandLineWrapper


def main(args:typing.Iterable[str])->int:
    """
    This generates a command line wrapper... from the command line.
    """
    printhelp=False
    cmd=None
    infoFrom:typing.List[str]=[]
    out=[]
    for arg in args:
        if cmd is None:
            if arg[0]=='-':
                if arg[1]=='-':
                    arg=arg.split('=',1)
                    if arg[0]=='--out':
                        out.append(arg[-1])
                    else:
                        print('Unrecognized parameter: '+arg[0])
                        printhelp=True
                else:
                    print('Unrecognized parameter: '+arg)
                    printhelp=True
            else:
                cmd=arg
        else:
            infoFrom.append(arg)
    if cmd is None:
        print('ERR: no cmd specified.')
        printhelp=True
    if len(out)<1:
        print('ERR: no outputs specified.')
        printhelp=True
    if printhelp:
        print('USAGE:')
        print('\tcmdlinewrapper.py --out=filename [--out=filename ...] cmd [get_info_from]') # noqa: E501 # pylint: disable = line-too-long
        print('PARAMS:')
        print('\t--out=<filename> ..... output to save.  If filename is just an extension, save to stdout.') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcurrently supports: only ".py"')
        print('EXAMPLES:')
        print('\tAutomatically generate python wrapper for "ls" to the file "ls.py":') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcmdlinewrapper.py --out=ls.py ls')
        print('\tAutomatically generate python wrapper for "ls" to stdout:')
        print('\t\tcmdlinewrapper.py --out=.py ls')
        print('\tGenerate the wrapper by calling the command with --help:')
        print('\t\tcmdlinewrapper.py --out=.py ls ls --help')
        print('\t... or just let cmdlinewrapper make the assumption:')
        print('\t\tcmdlinewrapper.py --out=.py ls --help')
        print('\tGenerate the wrapper from the command\'s manpage:')
        print('\t\tcmdlinewrapper.py --out=.py ls man')
        print('\tGenerate the wrapper from a webpage:')
        print('\t\tcmdlinewrapper.py --out=.py ls http://www.foo.com/ls.html')
        print('\t... or a local file:')
        print('\t\tcmdlinewrapper.py --out=.py ls ls.html')
        print('\t... same goes for text files:')
        print('\t\tcmdlinewrapper.py --out=.py ls README.txt')
        return -1
    wrapper=CmdLineWrapper(cmd)
    wrapper.getCommandLineOptions(' '.join(infoFrom))
    for o in out:
        extn=o.rsplit('.',1)
        if extn[-1]=='py':
            if len(extn)<2 or extn[0]=='' or extn[0]=='-':
                print(wrapper.createPythonWrapper(createMainFunction=True))
            else:
                wrapper.savePythonWrapper(o,createMainFunction=True)
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv[1:]))
