#!/usr/bin/python
"""
This is helper for creating function calls that run command line
programs
"""
import typing
import os
from pathlib import Path
from paths import asUrl,UrlCompatible
from .helpfiles import CommandLineOption, HelpSystemEntry
from .asCommandLine import CommandLineCompatible
from .commandLineStringHelpers import commandlineSplit
if typing.TYPE_CHECKING:
    from k_runner import (
        DataRecievedCallbacks,EnvironmentVariablesCompatible,
        OsRunJob,OsRunResult)


class CommandLineWrapper(HelpSystemEntry):
    """
    A tool to create function calls from command line apps
    """
    def __init__(self,
        app:typing.Optional[CommandLineCompatible]=None):
        HelpSystemEntry.__init__(self,app)

    @typing.overload
    def __getitem__(self,idx:slice)->list[CommandLineOption]:
        ...
    @typing.overload
    def __getitem__(self,idx:int)->CommandLineOption:
        ...
    def __getitem__(self,idx:typing.Union[int,slice]
        )->typing.Union[CommandLineOption,list[CommandLineOption]]:
        return self.commandLineOptions[idx]

    def createPythonWrapperCode(self,
        createMainFunction:bool=False,
        tabFormat:str='    '
        )->str:
        """
        Create python code (in a string) that wraps the command line call

        :createMainFunction: Generally, creating a command line
            app to call a command line app is
            rather pointless.  Still, can be handy for testing.
        """
        opts=tuple(self.getCommandLineOptions())
        if len(opts)<1:
            return ''
        code:typing.List[str]=[]
        code.append('#!/usr/bin/python')
        code.append('"""')
        code.append(f'This is wrapper for the "{self.name}" command line program') # noqa: E501 # pylint: disable = line-too-long
        if self.description:
            code.append('')
            for line in self.getDescription(False,True).split('\n'):
                code.append(line)
        code.append('')
        code.append('Generated by: The commandLine.py utility')
        code.append('"""')
        code.append('\n')
        code.append(f'def {self.name}(*args,**kwargs):')
        code.append(f'def {self.name}(*args,**kwargs):')
        code.append('\t"""')
        if self.description:
            code.append('\tDESCRIPTION:')
            for line in self.getDescription(False,True).split('\n'):
                code.append('\t\t'+line)
        code.append('\tPARAMETERS:')
        for o in opts:
            code.append('\t\t'+o.getHelp())
        code.append('\tRETURNS:')
        code.append('\t\tout,err')
        code.append('\t"""')
        code.append('\toptions={')
        for o in opts:
            opt=''
            for opt in o.options:
                break
            opt=opt.replace('[','').replace(']','')
            code.append('\t\t\''+o.name+'\':[\''+opt+'\'],')
        code.append('\t}')
        # TODO: May want to check if the app exists first??
        code.append(f'\tcmd=\'{self.app}\'')
        code.append('\tfor k,v in kwargs.items():')
        code.append('\t\tif options.has_key(k):')
        code.append('\t\t\to=options[k][0].split(\'=\',1)')
        code.append('\t\t\tcmd=cmd+\' \'+o[0]')
        code.append('\t\t\tif len(o)>1:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\'="\'+(\' \'.join(v))+\'"\'')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+\'=\'+str(v)')
        code.append('\t\t\telse:')
        code.append('\t\t\t\tif type(v)==list:')
        code.append('\t\t\t\t\tcmd=cmd+\' \'+(\' \'.join(v))')
        code.append('\t\t\t\telif v is not None:')
        code.append('\t\t\t\t\tcmd=cmd+str(v)')
        code.append('\t\telse:')
        code.append('\t\t\tprint \'WARN: Unregistered arg: \'+k')
        code.append('\tif len(args)>0:')
        code.append('\t\tcmd=cmd+\' \'+(\' \'.join(args))')
        # TODO: Add any option parameters here
        code.append('\tprint \'Calling: \\n   \'+cmd # Uncomment for debugging purposes') # noqa: E501 # pylint: disable = line-too-long
        code.append('\timport subprocess')
        code.append('\tout,err=subprocess.Popen(cmd,stderr=subprocess.PIPE,stdout=subprocess.PIPE,shell=True).communicate()') # noqa: E501 # pylint: disable = line-too-long
        code.append('\treturn out,err')
        if createMainFunction:
            code.append('\n')
            code.append('if __name__ == \'__main__\':')
            code.append('\timport sys')
            code.append('\titems=[]')
            code.append('\toptions={}')
            code.append('\ttry: # in newer python, we can preserve argument ordering!') # noqa: E501 # pylint: disable = line-too-long
            code.append('\t\tfrom collections import OrderedDict')
            code.append('\t\toptions=OrderedDict()')
            code.append('\texcept:')
            code.append('\t\tpass')
            code.append('\tdef AddOption(opt):')
            code.append('\t\topt=opt.split(\'=\',1)')
            code.append('\t\tif len(opt)>1:')
            code.append('\t\t\toptions[opt[0]]=opt[1]')
            code.append('\t\telse:')
            code.append('\t\t\toptions[opt[0]]=None')
            code.append('\tfor arg in sys.argv[1:]:')
            code.append('\t\tif arg[0]==\'-\':')
            code.append('\t\t\tif arg[1]==\'-\':')
            code.append('\t\t\t\tAddOption(arg[2:])')
            code.append('\t\t\telse:')
            code.append('\t\t\t\tfor a in arg[1:]:')
            code.append('\t\t\t\t\tAddOption(a)')
            code.append('\t\telse:')
            code.append('\t\t\titems.append(arg)')
            code.append(f'\tout,err={self.name}(*items,**options)')
            code.append('\terr=err.strip()')
            code.append('\tif err!=\'\':')
            code.append('\t\tprint err')
            code.append('\telse:')
            code.append('\t\tprint out')
        return '\n'.join(code).replace('\t',tabFormat)
    createPythonWrapper=createPythonWrapperCode

    def savePythonWrapper(self,
        filename:UrlCompatible,
        createMainFunction:bool=False
        )->bool:
        """
        Create a python wrapper for the command line application
        and save it to file
        """
        filename=asUrl(filename)
        data=self.createPythonWrapper(createMainFunction=createMainFunction)
        if data:
            filename.write(data)
            return True
        print('ERR: No data found.  File not saved.')
        return False
CommandLineParameterInfo=CommandLineWrapper
CmdLineParameterInfo=CommandLineParameterInfo


class ArgView:
    """
    Just the args to a program, that is
    argv only without the program name.
    """
    def __init__(self,allArgs:"CommandLineArguments"):
        self.allArgs=allArgs

    def __iter__(self):
        """
        Access like an array of parameter strings
        """
        return self.allArgs[1:]

    def __len__(self):
        """
        Access like an array of parameter strings
        """
        return len(self.allArgs)-1

    @typing.overload
    def __getitem__(self,idx:slice)->typing.Iterable[str]:
        """
        Access like an array of parameter strings
        """
    @typing.overload
    def __getitem__(self,idx:int)->str:
        """
        Access like an array of parameter strings
        """
    def __getitem__(self,
        idx:typing.Union[int,slice]
        )->typing.Iterable[str]:
        """
        Access like an array of parameter strings
        """
        if isinstance(idx,slice):
            idx=slice(idx.start+1,idx.stop+1,idx.step)
        else:
            idx+=1
        return self.allArgs[idx]

    def __setitem__(self,idx:int,val:str)->None:
        """
        Access like an array of parameter strings
        """
        self.allArgs[idx+1]=val

    def __delitem__(self,idx:int)->None:
        """
        Access like an array of parameter strings
        """
        del self.allArgs[idx+1]


class CommandLineArguments:
    """
    Wrap command line arguments in a more useful way
    """
    def __init__(self,
        *allArgs:typing.Union[CommandLineCompatible,None],
        invalidOsChars:typing.Union[str,typing.Iterable[str],None]=None):
        """ """
        self._argv:typing.List[str]=[]
        if invalidOsChars is None:
            invalidOsChars=os.name
        if isinstance(invalidOsChars,str):
            if invalidOsChars=='nt':
                # TODO: do this better
                invalidOsChars=('&','|',';','@')
            else:
                invalidOsChars=('&','|',';','@')
        self.invalidOsChars:typing.Iterable[str]=invalidOsChars
        for args in allArgs:
            if args is not None:
                self.append(args)

    @property
    def args(self)->ArgView:
        """
        Just the args
        (that is, without the program name)

        You can still modify them and the
        results will be reflected in the output
        """
        return ArgView(self)

    @property
    def parameterInfo(self)->CommandLineParameterInfo:
        """
        Try and find information
        """
        return CommandLineParameterInfo(self)

    def __iter__(self)->typing.Iterator[str]:
        """
        Access like an array of parameter strings
        """
        return iter(self._argv)

    def __len__(self)->int:
        """
        Access like an array of parameter strings
        """
        return len(self._argv)

    @typing.overload
    def __getitem__(self,idx:slice)->typing.Iterable[str]:
        """
        Access like an array of parameter strings
        """
    @typing.overload
    def __getitem__(self,idx:int)->str:
        """
        Access like an array of parameter strings
        """
    def __getitem__(self,
        idx:typing.Union[int,slice]
        )->typing.Iterable[str]:
        """
        Access like an array of parameter strings
        """
        return self._argv[idx]

    def __setitem__(self,idx:int,val:str)->None:
        """
        Access like an array of parameter strings
        """
        self._argv[idx]=val

    def __delitem__(self,idx:int)->None:
        """
        Access like an array of parameter strings
        """
        del self._argv[idx]

    def runAsync(self,
        shell:bool=False,
        detach:bool=False,
        debug:bool=False,
        workingDirectory:typing.Union[None,str,Path]=None,
        environmentVariables:typing.Optional[
            EnvironmentVariablesCompatible]=None,
        runCallbacks:typing.Optional[DataRecievedCallbacks]=None,
        priority:float=0.5,
        ansiHandling:str="strip",
        showHidden:bool=False,
        showMinimized:bool=False,
        showMaximized:bool=False,
        env:typing.Optional[
            EnvironmentVariablesCompatible]=None # alias for compatability
        )->"OsRunJob":
        """
        Generally speaking, this is backwards and you
        should osRun(commandline) instead.
        """
        from k_runner import OsRun
        job=OsRun(self,
            shell=shell,detach=detach,debug=debug,
            workingDirectory=workingDirectory,
            environmentVariables=environmentVariables,
            runCallbacks=runCallbacks,
            priority=priority,
            ansiHandling=ansiHandling,
            showHidden=showHidden,
            showMinimized=showMinimized,
            showMaximized=showMaximized,
            env=env).runAsync()
        return job

    def run(self,
        shell:bool=False,
        detach:bool=False,
        debug:bool=False,
        workingDirectory:typing.Union[None,str,Path]=None,
        environmentVariables:typing.Optional[
            EnvironmentVariablesCompatible]=None,
        runCallbacks:typing.Optional[DataRecievedCallbacks]=None,
        priority:float=0.5,
        ansiHandling:str="strip",
        showHidden:bool=False,
        showMinimized:bool=False,
        showMaximized:bool=False,
        env:typing.Optional[
            EnvironmentVariablesCompatible]=None # alias for compatability
        )->"OsRunResult":
        """
        Generally speaking, this is backwards and you
        should osRun(commandline) instead.
        """
        from k_runner import OsRun
        result=OsRun(self,
            shell=shell,detach=detach,debug=debug,
            workingDirectory=workingDirectory,
            environmentVariables=environmentVariables,
            runCallbacks=runCallbacks,
            priority=priority,
            ansiHandling=ansiHandling,
            showHidden=showHidden,
            showMinimized=showMinimized,
            showMaximized=showMaximized,
            env=env).run()
        return result
    __call__=run

    @property
    def name(self)->str:
        """
        The name of the executable
        """
        if not self._argv:
            return ''
        return self._argv[0]
    @name.setter
    def name(self,name:str):
        if not self._argv:
            self._argv.append(name)
        else:
            self._argv[0]=name

    def append(self,args:typing.Union[CommandLineCompatible,None]=None):
        """
        Add more arguments to the command line
        """
        if args is None:
            return
        if hasattr(args,'args') and not isinstance(args,CommandLine):
            args=typing.cast(CommandLineCompatible,args.args) # type: ignore
        if isinstance(args,Path):
            args=str(args)
        elif isinstance(args,str):
            p,a=commandlineSplit(args)
            args=[p]
            args.extend(a)
        if not isinstance(args,(list,tuple,CommandLine)):
            raise NotImplementedError(f'WARN: coercing type "{type(args)}" to a command line is not yet supported!') # noqa: E501 # pylint: disable=line-too-long
        for arg in args: # type: ignore
            self._argv.append(arg) # type: ignore
    extend=append

    def assign(self,args:typing.Union[CommandLineCompatible,None]=None):
        """
        Change the arguments
        """
        self.clear()
        self.append(args)

    def clear(self)->None:
        """
        Clear the arguments
        """
        self._argv.clear()

    def commandLineArgs(self,shellReplace:bool=False)->typing.Iterable[str]:
        """
        Get command line args list of values.
        """
        if shellReplace:
            try:
                import osTools
                args=osTools.expandvars(self._argv)
            except ImportError as e:
                print(e)
        args=self._argv
        return [self._shellEscape(arg) for arg in args]

    def asString(self,
        shellReplace:bool=False
        )->str:
        """
        Get as a string
        """
        args=self.commandLineArgs(shellReplace)
        return ' '.join([self._enquote(arg) for arg in args])
    toString=asString

    def _enquote(self,s:str)->str:
        if ' ' in s:
            s=s.replace('\\\\','\\').replace('"','\\"')
            return f'"{s}"'
        return s

    def _shellEscape(self,s:str)->str:
        """
        Shell escape the args
        """
        if isinstance(s,Path):
            return s # This is good by definition
        s=str(s)
        for c in self.invalidOsChars:
            s=s.replace(c,'\\'+c)
        return s

    def encodeToArray(self)->typing.List[str]:
        """
        In preparation for calling, this encodes all of the
        values to an array of shell-escaped values.
        """
        return [self._shellEscape(v) for v in self._argv]

    def __repr__(self)->str:
        return self.asString()
CommandLine=CommandLineArguments
CmdLine=CommandLineArguments


def main(args:typing.Iterable[str])->int:
    """
    This generates a command line wrapper... from the command line.
    """
    printHelp=False
    cmd=None
    infoFrom:typing.List[str]=[]
    out:typing.List[str]=[]
    for arg in args:
        if cmd is None:
            if arg[0]=='-':
                if arg[1]=='-':
                    arg=arg.split('=',1)
                    if arg[0]=='--out':
                        out.append(arg[-1])
                    else:
                        print('Unrecognized parameter: '+arg[0])
                        printHelp=True
                else:
                    print('Unrecognized parameter: '+arg)
                    printHelp=True
            else:
                cmd=arg
        else:
            infoFrom.append(arg)
    if cmd is None:
        print('ERR: no cmd specified.')
        printHelp=True
    if len(out)<1:
        print('ERR: no outputs specified.')
        printHelp=True
    if printHelp:
        print('USAGE:')
        print('\tcommandLine.py --out=filename [--out=filename ...] cmd [get_info_from]') # noqa: E501 # pylint: disable = line-too-long
        print('PARAMS:')
        print('\t--out=<filename> ..... output to save.  If filename is just an extension, save to stdout.') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcurrently supports: only ".py"')
        print('EXAMPLES:')
        print('\tAutomatically generate python wrapper for "ls" to the file "ls.py":') # noqa: E501 # pylint: disable = line-too-long
        print('\t\tcommandLine.py --out=ls.py ls')
        print('\tAutomatically generate python wrapper for "ls" to stdout:')
        print('\t\tcommandLine.py --out=.py ls')
        print('\tGenerate the wrapper by calling the command with --help:')
        print('\t\tcommandLine.py --out=.py ls ls --help')
        print('\t... or just let commandLine make the assumption:')
        print('\t\tcommandLine.py --out=.py ls --help')
        print('\tGenerate the wrapper from the command\'s manpage:')
        print('\t\tcommandLine.py --out=.py ls man')
        print('\tGenerate the wrapper from a webpage:')
        print('\t\tcommandLine.py --out=.py ls http://www.foo.com/ls.html')
        print('\t... or a local file:')
        print('\t\tcommandLine.py --out=.py ls ls.html')
        print('\t... same goes for text files:')
        print('\t\tcommandLine.py --out=.py ls README.txt')
        return -1
    wrapper=CmdLineParameterInfo(cmd)
    wrapper.getCommandLineOptions(' '.join(infoFrom))
    for o in out:
        extension=o.rsplit('.',1)
        if extension[-1]=='py':
            if len(extension)<2 or extension[0]=='' or extension[0]=='-':
                print(wrapper.createPythonWrapper(createMainFunction=True))
            else:
                wrapper.savePythonWrapper(o,createMainFunction=True)
    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main(sys.argv[1:]))
